version: '3'

services:
  node_app:
    container_name: tf_backend
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DB_NAME=wtowxche
      - DB_PASSWORD=cVELqqovWrErefoKYY2bvP-aqmSCa2HQ
      - DB_USER=wtowxche
      - DB_HOST=suleiman.db.elephantsql.com
      - JWT_SECRET_KEY=R5#Vt@p8$2MnKuSvW1yZ%qJk3Hn4Gf&7
      - EMAIL_SERVICE=Gmail
      - EMAIL_USER=moussamoustaphamoussa37@gmail.com
      - EMAIL_PASSWORD=gzzp cuti kvxt ubio
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sdvvlfvu
      POSTGRES_PASSWORD: e-tXA8_NwTGLhqU0JfDcJ7YaZKZB91Hf
      POSTGRES_DB: sdvvlfvu

